######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 20 18:19:36 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyClient.h ../commands.h ../servclient.h \
    mainwindow.h
SOURCES += main.cpp MyClient.cpp ../servclient.cpp \
    mainwindow.cpp

QT += network gui
